First sprint
ClevertecFrontendLab/sprint1-lustojc pull request #1
Opened 2023-01-30 18:24 UTC by lustojc

2023-01-30 18:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675103222/content-window.png)

2023-01-30 18:51 UTC, klichkovskiy requested changes

2023-01-30 18:51 UTC, klichkovskiy commented on src/index.tsx
> +import React from 'react';
шрифт не по макету. Перепроверь

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +        {book.rating === null ? (
![image](https://user-images.githubusercontent.com/62481116/215566587-ada0e8db-f0de-4b38-9272-27ce3cf68ee3.png)
не по макету на 320

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +            Отзывы <span>0</span>
![image](https://user-images.githubusercontent.com/62481116/215566766-56719cf7-fbb5-4bba-8228-04a3421899b5.png)
не по макету. должно быть по одной линии

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +        <div className='book-page__review'>
это нужно промапать

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +      <div className='book-page__map'>
![image](https://user-images.githubusercontent.com/62481116/215567138-69c3e5bf-ff01-45e8-bd80-bfa26cd6079b.png)
Где бэкграунд?

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +  console.log(category, bookId);
убрать консольку

2023-01-30 18:51 UTC, klichkovskiy commented on src/components/card/card.tsx
> +  const title = el.title.substring(0, 54) + '...';
Есть css свойства для этого!

2023-01-30 18:51 UTC, klichkovskiy commented on src/components/navigation/navigation.tsx
> +  const bookTypes = [
в отдельный файл вынести

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +  const books = [
тоже в отдельную константу вынести

2023-01-30 18:51 UTC, klichkovskiy commented on src/pages/term/term.scss
> +  //   &-block1 {
удалить закомментированные части

2023-02-01 13:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/lustojc/1675256896/content-window.png)

2023-02-01 13:21 UTC, klichkovskiy approved these changes

2023-02-01 14:17 UTC, merged